### ISSUE TITLE
Endpoints

### ISSUE THREAD

**Issue by Juzzle1** [sfjuocekr/SBUS-joystick#1]
Hey,

Thanks for sharing this!

Any reason you set the SBUS startpoint and endpoint to 240 / 1807 instead of  the SBUS library defaults of 172 / 1811?

I've quickly tested your precompiled hex and had to limit the mixer outputs on my radio to 90% as when channels go below the startpoint value they flip round to the max value.... so min throttle on my radio = max throttle in the sim.

Maybe needs a sanity check to see if input < startpoint or input > endpoint and if so, override and set them to startpoint / endpoint accordingly?

Hope that makes sense.

Otherwise this works great! .. will be putting it in a project box along with HDMI to AV converter, 5.8GHz TX and an X4R reciever for fully wire-free sim :)

**Comment by sfjuocekr** [comment]
Shit I just remembered I never answered your issue!

I had these, apparently non-default, endpoints because it just worked with my radio.

The flip around behavior could be modified to be just linear, I'll change it to some more sane defaults or just go back to the old auto calibration.

**Comment by sfjuocekr** [comment]
I've updated it with defaults and constrained the output from 0 to 65535.
